### ISSUE TITLE
textobj#user#plugin not found

### ISSUE THREAD

**Issue by akiradeveloper** [kana/vim-textobj-indent#4]
After installing vim-textobj-indent plugin under bundle/, vim began to complain

Error detected while processing /home/akira/dotfiles/.vim/bundle/vim-textobj-indent/plugin/textobj/indent.vim:
line   48:
E117: Unknown function: textobj#user#plugin

so, where is the definition of textobj#user#plugin? I couldn't find it. Isn't it implemented yet?

**Comment by kana** [comment]
[RTFM](https://github.com/kana/vim-textobj-indent/blob/63b0014838515b3f2b465c997bb984d5579ddfa7/doc/textobj-indent.txt#L93).

**Comment by MahbubAlam231** [comment]
How do you fix the error "Unknown function: textobj#user#plugin"? I don't get it.
